global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds.

rule_files:
  - "alert.rule"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nodeexporter'
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']


  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']

  